EMSI_Corporation/Controllers/ServicioController.cs
using EMSI_Corporation.Data;
using EMSI_Corporation.Models;
using EMSI_Corporation.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EMSI_Corporation.Controllers
{
    public class ServicioController : Controller
    {
        private readonly AppDBContext _appDBContext;
        //prueba
        public ServicioController(AppDBContext appDBContext)
        {
            _appDBContext = appDBContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SeleccionClienteTrabajador()
        {
            ViewBag.Clientes = _appDBContext.Clientes.ToList();
            ViewBag.Trabajadores = _appDBContext.empleados.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult SeleccionClienteTrabajador(ClienteTrabajadorVM ctVM)
        {
            //ViewBag.extintor = ext;//se supone que ya no
            ViewBag.mantenimientos = new List<Mantenimiento>();
            ctVM.cliente = _appDBContext.Clientes.Find(ctVM.clienteID);
            ctVM.empleado = _appDBContext.empleados.Find(ctVM.empleadoID);
            //ViewBag.cliente_trabajador = ctVM;
            if (ctVM.TipoServicio == "Mantenimiento")
            {
                return RedirectToAction("Registrar", "Mantenimiento", ctVM);
            }
            else
            {
                return RedirectToAction("Registrar", "Recarga", ctVM);
            }
        }
    }
}

EMSI_Corporation/Views/Servicio/SeleccionClienteTrabajador.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var clientes = ViewBag.Clientes as List<EMSI_Corporation.Models.Cliente>;
    var trabajadores = ViewBag.Trabajadores as List<EMSI_Corporation.Models.Empleado>;
}
@model EMSI_Corporation.ViewModels.ClienteTrabajadorVM;


    <div class="seccion">
        <form class="modal-content" asp-controller="Servicio" asp-action="SeleccionCLienteTrabajador" method="post">
            <div class="modal-header">
                <h1 class="titulo">Cliente / Trabajador</h1>
            </div>
            <div class="modal-body d-flex flex-column gap-4">

                <div class="form-line">
                    <span>Empresa:</span>
                    <select class="field" asp-for="clienteID">
                        @foreach (var cliente in clientes)
                        {
                            <option value=@cliente.IdCliente>@cliente.NomCliente</option>
                        }
                    </select>
                </div>
                <div class="form-line">
                    <span>Trabajador:</span>
                    <select class="field" asp-for="empleadoID">
                        @foreach (var trabajador in trabajadores)
                        {
                            <option value=@trabajador.IdEmpleado>@trabajador.nomEmpleado</option>
                        }
                    </select>
                </div>
            <div class="form-line">
                <span>Tipo de servicio:</span>
                <select class="field" asp-for="TipoServicio">
                    <option value="Mantenimiento">Mantenimiento</option>
                    <option value="Recarga">Recarga</option>
                </select>
            </div>
            </div>
            <div class="modal-footer d-flex flex-row justify-content-center">
                <button id="continue-btn" type="submit" class="btn-1">Ir a registrar</button>
            </div>
        </form>
    </div>