EMSI_Corporation/Models/Venta.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EMSI_Corporation.Models
{
    public class Venta
    {
        [Key]
        public int IdVenta { get; set; }
        public DateTime FechaVenta { get; set; }
        public string MetodoPago { get; set; }
        public decimal Total { get; set; }

        [ForeignKey("Cliente")]
        public int Cliente_ID { get; set; }
        public Cliente Cliente { get; set; }

        [ForeignKey("Empleado")]
        public int Empleado_ID { get; set; }
        public Empleado Empleado { get; set; }
    }
}

EMSI_Corporation/Controllers/VentaController.cs
using EMSI_Corporation.Data;
using EMSI_Corporation.Models;
using EMSI_Corporation.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EMSI_Corporation.Controllers
{

    public class VentaController : Controller
    {
        private readonly AppDBContext _appDBContext;

        public VentaController(AppDBContext appDBContext)
        {
            _appDBContext = appDBContext;
        }
        public IActionResult Index()
        {
            var ventas = _appDBContext.Ventas.ToList();
            var extintores = _appDBContext.Extintores.ToList();

            for (int i = 0; i < ventas.Count; i++)
            {
                ventas[i].Cliente = _appDBContext.Clientes.Find(ventas[i].Cliente_ID);
                ventas[i].Empleado = _appDBContext.empleados.Find(ventas[i].Empleado_ID);
            }

            ViewBag.extintores = extintores;
            return View(ventas);
        }

        public IActionResult VentasPorId(int id)
        {
            var Extintor = _appDBContext.Extintores.Find(id);
            Venta vent = Extintor.Venta;
            ViewBag.ExtintorId = id;
            return View(vent);
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            ViewBag.clientes = _appDBContext.Clientes.ToList();
            ViewBag.empleados = _appDBContext.empleados.ToList();
            ViewBag.extintores = _appDBContext.Extintores.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(VentaVM ventaVM)
        {
            /*
            int hola = 0;
            if(int.TryParse(ventaVM.MetodoPago, out hola))
            {
                ViewBag.clientes = _appDBContext.Clientes.ToList();
                ViewBag.empleados = _appDBContext.empleados.ToList();
                ViewData["error"] = "Datos incorrectos";
                return View();

            }
            */
            try
            {
                int hola = 0;
                if (int.TryParse(ventaVM.MetodoPago, out hola))
                {
                    throw new Exception();

                }
                Cliente? cli = _appDBContext.Clientes.Find(ventaVM.Cliente_ID);
                Empleado? empleado = _appDBContext.empleados.Find(ventaVM.Empleado_ID);

                Venta venta = new Venta
                {
                    Cliente = cli,
                    Cliente_ID = ventaVM.Cliente_ID,
                    Empleado = empleado,
                    Empleado_ID = ventaVM.Empleado_ID,
                    FechaVenta = ventaVM.FechaVenta,
                    MetodoPago = ventaVM.MetodoPago,
                    Total = ventaVM.Total
                };
                _appDBContext.Ventas.Add(venta);
                _appDBContext.SaveChanges();

                Extintor ext = _appDBContext.Extintores.Find(ventaVM.Extintor_ID);
                ext.Venta_ID = venta.IdVenta;
                _appDBContext.Extintores.Update(ext);
                _appDBContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.clientes = _appDBContext.Clientes.ToList();
                ViewBag.empleados = _appDBContext.empleados.ToList();
                ViewBag.extintores = _appDBContext.Extintores.ToList();
                ViewData["error"] = "Datos incorrectos";
                return View();
            }
        }
    }
}

EMSI_Corporation/Views/Venta/Index.cshtml
@model List<EMSI_Corporation.Models.Venta>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var extintores = ViewBag.extintores as List<EMSI_Corporation.Models.Extintor>;
}

<main>
    <!--
        public int IdVenta { get; set; }
        public DateTime FechaVenta { get; set; }
        public string MetodoPago { get; set; }
        public decimal Total { get; set; }

        [ForeignKey("Cliente")]
        public int Cliente_ID { get; set; }
        public Cliente Cliente { get; set; }

        [ForeignKey("Empleado")]
        public int Empleado_ID { get; set; }
        public Empleado Empleado { get; set; }
    -->
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-primary" asp-controller="Venta" asp-action="Registrar" >Agregar Venta</a>
    </div>

    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Fecha de venta</th>
                <th>Método de pago</th>
                <th>Total</th>
                <th>Cliente</th>
                <th>Empleado</th>
                <th>Extintor</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var v in Model)
            {
                var ext = extintores.Find(e => e.Venta_ID == v.IdVenta);
                <tr>
                    <td>@v.IdVenta</td>
                    <td>@v.FechaVenta</td>
                    <td>@v.MetodoPago</td>
                    <td>@v.Total</td>
                    <td>@v.Cliente.NomCliente</td>
                    <td>@v.Empleado.IdEmpleado</td>
                    @if (ext != null)
                    {
                        <td>@ext.IdExtintor</td>
                    }
                </tr>


                
            }
        </tbody>
    </table>
</main>

EMSI_Corporation/Views/Venta/Registrar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model EMSI_Corporation.ViewModels.VentaVM;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var clientes = ViewBag.clientes as List<EMSI_Corporation.Models.Cliente>;
    var empleados = ViewBag.empleados as List<EMSI_Corporation.Models.Empleado>;
    var extintores = ViewBag.extintores as List<EMSI_Corporation.Models.Extintor>;
}

<!--public DateTime FechaVenta { get; set; }
    public string MetodoPago { get; set; }
    public decimal Total { get; set; }

    public int Cliente_ID { get; set; }
    public Cliente Cliente { get; set; }

    public int Empleado_ID { get; set; }
    public Empleado Empleado { get; set; }-->
<form class="seccion" method="post" asp-controller="Venta" asp-action="Registrar">
    <div class="form-line">
        <span>Fecha de venta:</span>
        <input class="field" placeholder="Fecha de venta" type="date" asp-for="FechaVenta" />
    </div>
    <div class="form-line">
        <span>Método de pago:</span>
        <input class="field" placeholder="Método de pago" type="text" asp-for="MetodoPago" />
    </div>
    <div class="form-line">
        <span>Pago total:</span>
        <input class="field" placeholder="Pago total" type="text" asp-for="Total" />
    </div>
    <div class="form-line">
        <span>Cliente:</span>
        <select class="field" asp-for="Cliente_ID">
            @foreach (Cliente cliente in clientes)
            {
                <option value=@cliente.IdCliente>@cliente.NomCliente</option>
            }
        </select>
    </div>
    <div class="form-line">
        <span>Empleado:</span>
        <select class="field" asp-for="Empleado_ID">
            @foreach (Empleado empleado in empleados)
            {
                <option value=@empleado.IdEmpleado>@empleado.nomEmpleado</option>
            }
        </select>
    </div>
    <div class="form-line">
        <span>Extintor:</span>
        <select class="field" asp-for="Extintor_ID">
            @foreach (Extintor extintor in extintores)
            {
                <option value=@extintor.IdExtintor>@extintor.IdExtintor</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Registrar</button>
</form>